version: "3.3"

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: clean_app_postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  backend:
    build: ./backend
    container_name: clean_app_backend
    restart: always
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_MINUTES=60
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    volumes:
      - static_data:/app/app/static
    networks:
      - app_network

  frontend:
    build: ./frontend
    container_name: clean_app_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  pg_data:
  static_data:

networks:
  app_network:
    driver: bridge
